trigger:
- '*'
pool: 
  name: Default
variables:
  buildConfig: 'Release'
steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.X'
  inputs:
    packageType: sdk
    version: '6.X'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Run npm install with node v18.16.0'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp Tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project -Release'
  inputs:
   command: 'build'
   arguments: '--no-restore --configuration Release'
   projects: '**/*.csproj'